import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { makeTempDir } from "./support/tmp.js";
import {
  elementState,
  readRecord,
  writeRecord,
  RECORD_FORMAT,
  type GenerationRecord,
} from "../src/baseline/record.js";
import { sha256 } from "../src/baseline/templates.js";
import {
  computeSkillFile,
  applySkillFile,
} from "../src/baseline/skill-file.js";

const cleanups: (() => void)[] = [];
afterEach(() => {
  while (cleanups.length > 0) cleanups.pop()?.();
});

function tempDir(): string {
  const { dir, cleanup } = makeTempDir();
  cleanups.push(cleanup);
  return dir;
}

describe("elementState (data-model §1.1)", () => {
  it("is missing when the file is absent", () => {
    expect(elementState(undefined, "template", null)).toBe("missing");
  });

  it("with no record entry: current when it matches the template, edited when it does not", () => {
    expect(elementState(undefined, "same", "same")).toBe("current");
    expect(elementState(undefined, "template", "user-edited")).toBe("edited");
  });

  it("with a record entry: current, outdated, or edited", () => {
    const entry = { path: "x", sha256: sha256("original"), release: "0.1.0" };
    // unedited, template unchanged
    expect(elementState(entry, "original", "original")).toBe("current");
    // unedited (hash matches record), but the template changed (a newer release)
    expect(elementState(entry, "new-template", "original")).toBe("outdated");
    // hash no longer matches the record at all: the user edited it
    expect(elementState(entry, "original", "user-changed-this")).toBe("edited");
    // hash no longer matches the record, even if it happens to equal the new template
    expect(elementState(entry, "user-changed-this", "user-changed-this")).toBe(
      "edited",
    );
  });
});

describe("readRecord / writeRecord (data-model §2)", () => {
  it("round-trips, sorted, with a trailing newline", () => {
    const dir = tempDir();
    const record: GenerationRecord = {
      format: RECORD_FORMAT,
      release: "0.1.0",
      elements: {
        "b-element": { path: "b", sha256: "bbb", release: "0.1.0" },
        "a-element": { path: "a", sha256: "aaa", release: "0.1.0" },
      },
    };
    writeRecord(dir, record);
    const raw = readFileSync(join(dir, ".domusops", "generated.json"), "utf8");
    expect(raw.endsWith("\n")).toBe(true);
    expect(raw.indexOf('"a-element"')).toBeLessThan(raw.indexOf('"b-element"'));
    expect(readRecord(dir)).toEqual(record);
  });

  it("a re-run with nothing to do writes byte-identical bytes", () => {
    const dir = tempDir();
    const record: GenerationRecord = {
      format: RECORD_FORMAT,
      release: "0.1.0",
      elements: { one: { path: "one", sha256: "111", release: "0.1.0" } },
    };
    writeRecord(dir, record);
    const first = readFileSync(join(dir, ".domusops", "generated.json"));
    writeRecord(dir, record);
    const second = readFileSync(join(dir, ".domusops", "generated.json"));
    expect(second.equals(first)).toBe(true);
  });

  it("returns null on a missing file, invalid JSON, or the wrong format (FR-029)", () => {
    const dir = tempDir();
    expect(readRecord(dir)).toBeNull();
    mkdirSync(join(dir, ".domusops"), { recursive: true });
    writeFileSync(join(dir, ".domusops", "generated.json"), "not json");
    expect(readRecord(dir)).toBeNull();
    writeFileSync(
      join(dir, ".domusops", "generated.json"),
      JSON.stringify({
        format: "something-else/0.1",
        release: "x",
        elements: {},
      }),
    );
    expect(readRecord(dir)).toBeNull();
  });

  it("a missing or unusable record treats every differing skill-owned element as edited (FR-029)", () => {
    const dir = tempDir();
    const path = join(dir, "some-file.txt");
    writeFileSync(path, "hand-written content, never generated by the skill");
    // No record at all.
    const noRecord = computeSkillFile(
      path,
      "the current template",
      null,
      "some-element",
    );
    expect(noRecord.state).toBe("edited");
    // A damaged record (same effect as null, since readRecord already returns null for it, but
    // exercise computeSkillFile directly with an unrelated record that has no entry for this id).
    const unrelated: GenerationRecord = {
      format: RECORD_FORMAT,
      release: "0.1.0",
      elements: {},
    };
    const noEntry = computeSkillFile(
      path,
      "the current template",
      unrelated,
      "some-element",
    );
    expect(noEntry.state).toBe("edited");
  });
});

describe("outdated → rewrite across a simulated release bump", () => {
  it("an unedited skill-owned file is rewritten to the new template; an edited one is not", () => {
    const dir = tempDir();
    const unedited = join(dir, "unedited.txt");
    const edited = join(dir, "edited.txt");
    const oldTemplate = "template for release 0.1.0";
    const newTemplate = "template for release 0.2.0";

    // First "release": both files created from the old template.
    applySkillFile(unedited, oldTemplate, null, "unedited-element");
    applySkillFile(edited, oldTemplate, null, "edited-element");
    const record: GenerationRecord = {
      format: RECORD_FORMAT,
      release: "0.1.0",
      elements: {
        "unedited-element": {
          path: "unedited.txt",
          sha256: sha256(oldTemplate),
          release: "0.1.0",
        },
        "edited-element": {
          path: "edited.txt",
          sha256: sha256(oldTemplate),
          release: "0.1.0",
        },
      },
    };
    writeRecord(dir, record);

    // The user edits one of them by hand.
    writeFileSync(edited, "the user's own version, not the template");

    // A newer release: applying the new template upgrades the unedited file and leaves the
    // edited one untouched (FR-022).
    const uneditedResult = applySkillFile(
      unedited,
      newTemplate,
      record,
      "unedited-element",
    );
    const editedResult = applySkillFile(
      edited,
      newTemplate,
      record,
      "edited-element",
    );
    expect(uneditedResult.state).toBe("outdated");
    expect(readFileSync(unedited, "utf8")).toBe(newTemplate);
    expect(editedResult.state).toBe("edited");
    expect(readFileSync(edited, "utf8")).toBe(
      "the user's own version, not the template",
    );
  });
});
